version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8004:8004
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - services-network
    environment:
      DATABASE_URL: mysql://root:root@db:3306/user  

  db:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: messageService
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - services-network

networks:
  services-network:
    external: true

